### ISSUE TITLE
postgres:backup-schedule returns "Invalid flag provided, only '--use-iam' allowed"

### ISSUE THREAD

**Issue by redhoodie** [dokku/dokku-postgres#143] opened 2018-04-29 21:48 UTC
This could just be me making a n00b mistake;

Whenever I run `postgres:backup-schedule` to update a postgresql backup schedule I get the following error;

> Invalid flag provided, only '--use-iam' allowed

```
michael$ ssh dokku@server postgres:backup-schedule some-postgres-name "0 3 * * *" some-bucket
Invalid flag provided, only '--use-iam' allowed
Connection to server-ip closed.
```

**Comment by undecided** [comment] 2018-05-26 15:10
I've seen this too today - the issue is SSH. It ignores the quotes in the schedule - so where dokku expects a single param containing spaces, ssh expands it to 5 separate params. It would be nice if dokku could replace any underscores for spaces maybe?

**Comment by josegonzalez** [comment] 2018-05-26 20:45
Have you tried escaping quotes when using them over a shell? https://stackoverflow.com/a/20498919/1515875

**Comment by josegonzalez** [comment] 2018-12-02 09:43
Closing. I think the issue here might be more related to how the commands get sent over ssh, and since thats a protocol we don't have much control over, there isn't any real fix.

You could probably get around this by setting the schedule to something like `@daily`.

**Closed by josegonzalez** 2018-12-02 09:43 UTC
